name: Release

on:
  release:
    types:
      - published

jobs:
  release:
    name: 'Build, package and release to GitHub'
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3     

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.repository }}/kpnameer/wakapi
          tags: |
            latest
            alpine
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          

      - name: Prepare
        run: |
          cp ../config.gpg config.gpg

      - name: Run Docker container on the server using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          script: |
            echo "${{ secrets.CONFIG_YML_SECRET }}" > /home/ubuntu/deployments/wakapi/config.yml
            # Authenticate with GitHub Container Registry
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GITHUB_ACTOR }} --password-stdin
            
            # Pull Docker image from GitHub Container Registry
            docker pull ghcr.io/kpnameer/wakapi:latest
            
            # Run your Docker container
            docker run -d --name wakapi -p 3000:3000 ghcr.io/kpnameer/wakapi:latest 
